#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 08, 2020 12:05:13 PM GMT  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import control_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = ControlWindow (root)
    control_support.init(root, top)
    root.mainloop()

w = None
def create_ControlWindow(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = ControlWindow (w)
    control_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_ControlWindow():
    global w
    w.destroy()
    w = None

class ControlWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("200x131+1063+350")
        top.minsize(1, 1)
        top.maxsize(4465, 1410)
        top.resizable(1, 1)
        top.title("Control")
        top.configure(background="#212121")

        self.residuals_button = tk.Button(top)
        self.residuals_button.place(relx=0.05, rely=0.076, height=31, width=141)
        self.residuals_button.configure(activebackground="#898989")
        self.residuals_button.configure(background="#636363")
        self.residuals_button.configure(highlightbackground="#636363")
        self.residuals_button.configure(relief="flat")
        self.residuals_button.configure(text='''Residuals''')

        self.wall_shear_button = tk.Button(top)
        self.wall_shear_button.place(relx=0.05, rely=0.382, height=31, width=141)

        self.wall_shear_button.configure(activebackground="#898989")
        self.wall_shear_button.configure(background="#636363")
        self.wall_shear_button.configure(highlightbackground="#636363")
        self.wall_shear_button.configure(relief="flat")
        self.wall_shear_button.configure(text='''Wall Shear''')

        self.wall_shear_wm_button = tk.Button(top)
        self.wall_shear_wm_button.place(relx=0.05, rely=0.687, height=31
                , width=141)
        self.wall_shear_wm_button.configure(activebackground="#898989")
        self.wall_shear_wm_button.configure(background="#636363")
        self.wall_shear_wm_button.configure(highlightbackground="#636363")
        self.wall_shear_wm_button.configure(relief="flat")
        self.wall_shear_wm_button.configure(text='''Wall Shear (WM)''')

        self.residuals_edit_button = tk.Button(top)
        self.residuals_edit_button.place(relx=0.8, rely=0.076, height=31
                , width=31)
        self.residuals_edit_button.configure(activebackground="#898989")
        self.residuals_edit_button.configure(background="#636363")
        self.residuals_edit_button.configure(highlightbackground="#636363")
        self.residuals_edit_button.configure(relief="flat")

        self.wall_shear_edit_button = tk.Button(top)
        self.wall_shear_edit_button.place(relx=0.8, rely=0.382, height=31
                , width=31)
        self.wall_shear_edit_button.configure(activebackground="#898989")
        self.wall_shear_edit_button.configure(background="#636363")
        self.wall_shear_edit_button.configure(highlightbackground="#636363")
        self.wall_shear_edit_button.configure(relief="flat")

        self.wall_shear_wm_edit_button = tk.Button(top)
        self.wall_shear_wm_edit_button.place(relx=0.8, rely=0.687, height=31
                , width=31)
        self.wall_shear_wm_edit_button.configure(activebackground="#898989")
        self.wall_shear_wm_edit_button.configure(background="#636363")
        self.wall_shear_wm_edit_button.configure(highlightbackground="#636363")
        self.wall_shear_wm_edit_button.configure(relief="flat")

if __name__ == '__main__':
    vp_start_gui()





