#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 08, 2020 11:33:26 AM GMT  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import monitor_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = MainWindow (root)
    monitor_support.init(root, top)
    root.mainloop()

w = None
def create_MainWindow(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = MainWindow (w)
    monitor_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MainWindow():
    global w
    w.destroy()
    w = None

class MainWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("848x666+886+123")
        top.minsize(1, 1)
        top.maxsize(4465, 1410)
        top.resizable(1, 1)
        top.title("Monitor")
        top.configure(background="#212121")

        self.monitor_canvas = tk.Canvas(top)
        self.monitor_canvas.place(relx=0.012, rely=0.015, relheight=0.977
                , relwidth=0.98)
        self.monitor_canvas.configure(background="#111111")
        self.monitor_canvas.configure(highlightbackground="#000000")
        self.monitor_canvas.configure(relief="ridge")
        self.monitor_canvas.configure(selectbackground="#c4c4c4")

if __name__ == '__main__':
    vp_start_gui()





